// Generated by CoffeeScript 1.6.3
(function() {
  var createUrlParser;

  createUrlParser = function(url) {
    var parser;
    parser = document.createElement('a');
    parser.href = url;
    return parser;
  };

  $.responsiveWindowImage = function() {
    var height, laptop, mobile, tablet, width;
    width = $(window).width();
    height = $(window).height();
    console.log(width, height);
    mobile = [640, 960];
    tablet = [1024, 768];
    laptop = [1600, 1200];
    if (width <= mobile[0] && height <= mobile[1]) {
      console.log('mobile');
      return mobile;
    } else if (width <= tablet[0] && height <= tablet[1]) {
      console.log('tablet');
      return tablet;
    } else {
      console.log('laptop');
      return laptop;
    }
  };

  $.cloudinaryOptimize = function(url, options) {
    var height_limit, image_link, image_settings, parser, path_elements, settings, width_limit, _ref;
    parser = createUrlParser(url);
    if (parser.hostname !== 'res.cloudinary.com') {
      return parser;
    }
    _ref = $.responsiveWindowImage(), width_limit = _ref[0], height_limit = _ref[1];
    settings = {
      crop: true,
      width: width_limit,
      height: height_limit,
      quality: 70,
      blur: false
    };
    $.extend(settings, options);
    path_elements = parser.pathname.split('/');
    image_link = path_elements[5].split('.');
    if (image_link[1] !== 'jpg') {
      image_link[1] = 'jpg';
    }
    path_elements[5] = image_link.join('.');
    image_settings = ['c_fill', 'w_' + settings.width, 'h_' + settings.height, 'q_' + settings.quality];
    if (settings.blur) {
      image_settings.push('e_blur');
    }
    path_elements[4] = image_settings.join(',');
    parser.pathname = path_elements.join('/');
    return parser.href;
  };

}).call(this);
