// Generated by CoffeeScript 1.6.3
(function() {
  var createUrlParser;

  createUrlParser = function(url) {
    var parser;
    parser = document.createElement('a');
    parser.href = url;
    return parser;
  };

  $.responsiveImage = function() {
    return [1600, 1200];
  };

  $.cloudinaryOptimize = function(url, options) {
    var height_limit, image_link, image_settings, parser, path_elements, settings, width_limit, _ref;
    parser = createUrlParser(url);
    if (parser.hostname !== 'res.cloudinary.com') {
      return parser;
    }
    _ref = $.responsiveImage(), width_limit = _ref[0], height_limit = _ref[1];
    settings = {
      width: width_limit,
      height: height_limit,
      quality: 50,
      blur: false
    };
    $.extend(settings, options);
    path_elements = parser.pathname.split('/');
    image_link = path_elements[5].split('.');
    if (image_link[1] !== 'jpg') {
      image_link[1] = 'jpg';
    }
    path_elements[5] = image_link.join('.');
    image_settings = ['c_limit', 'w_' + settings.width, 'h_' + settings.height, 'q_' + settings.quality];
    if (settings.blur) {
      image_settings.push('e_blur');
    }
    path_elements[4] = image_settings.join(',');
    parser.pathname = path_elements.join('/');
    return parser.href;
  };

}).call(this);
